# Build manifest for `builds.sr.ht`
image: fedora/38

packages:
- ftp
- podman
- python3-docutils
- python3.7
- python3.8
- python3.9
- python3.10
- python3.11

sources:
- git+https://git.sr.ht/~sschwarzer/ftputil

tasks:
- configure: |
    cd ftputil
    export DOCKER=podman
    $DOCKER pull index.docker.io/stilliard/pure-ftpd
    make run_test_server
    python3.11 -m venv ~/ftputil_env
    source ~/ftputil_env/bin/activate
    pip install --no-color --progress-bar=off --upgrade pip
    pip install --no-color --progress-bar=off freezegun pytest tox
- test: |
    cd ftputil
    source ~/ftputil_env/bin/activate
    tox

triggers:
- action: email
  condition: failure
  to: sschwarzer@sschwarzer.net
