# Build manifest for `builds.sr.ht`
image: fedora/33

packages:
- ftp
- podman
- python3-docutils
- python36
- python37
- python38
- python39

sources:
- hg+https://hg.sr.ht/~sschwarzer/ftputil

tasks:
- configure: |
    cd ftputil
    export DOCKER=podman
    $DOCKER pull index.docker.io/stilliard/pure-ftpd
    make run_test_server
    python3.8 -m venv ~/ftputil_env
    source ~/ftputil_env/bin/activate
    pip install --no-color --progress-bar=off --upgrade pip
    pip install --no-color --progress-bar=off freezegun pytest tox
- test: |
    cd ftputil
    make docs
    source ~/ftputil_env/bin/activate
    tox

triggers:
- action: email
  condition: failure
  to: sschwarzer@sschwarzer.net
