# frozen_string_literal: true

source "https://rubygems.org"

# See https://jekyllrb.com/docs/step-by-step/01-setup/
gem "jekyll"

# See https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/
gem "minimal-mistakes-jekyll"
